FROM python:slim-buster
EXPOSE 5000
WORKDIR /app
# enables the use of cache
COPY requirements.txt .                 
RUN pip install -r requirements.txt
COPY . .
CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]
